### ISSUE TITLE
Nuget - публикация пакета последней версии

### ISSUE THREAD

**Issue by skuill** [K1llMan/Yandex.Music.Api#1]
**Привет!**

Прежде всего хочу сказать спасибо за доработку API ;)
В Nuget сейчас опубликована [старая версия пакета 2019 года](https://www.nuget.org/packages/Yandex.Music.Api/1.0.0) . Как насчет публикации nuget пакета последней версии?

**Comment by K1llMan** [comment]
Почему-то уведомления не приходят.

Я поищу, как можно настроить публикацию в Nuget, возможно добавлю.

**Comment by K1llMan** [comment]
Пакеты добавлены, находятся на проверке.
