### ISSUE TITLE
Зависают приложения Windows Forms

### ISSUE THREAD

**Issue by shuryak** [K1llMan/Yandex.Music.Api#15]
Использование библиотеки в приложениях Windows Forms (не важно, какой версии .NET Framework или даже .NET / .NET Core) ведёт к их вечному зависанию при вызове любого метода, обращающегося к API Яндекс Музыки _в любом месте_ приложения (в консольных программах библиотека работает нормально).

Например, следующий код, помещённый в конструктор формы вообще не даст отобразить форму, и приложение намертво зависнет:

```csharp
YandexMusicClient api = new();
MessageBox.Show(api.GetAuthQRLink());
```

**Comment by shuryak** [comment]
Оказалось, вызов **НЕ** любого метода заставляет приложение зависнуть. Так, например, асинхронные методы `Track.GetAsync` и `Search.TrackAsync` работают, а их синхронные версии — нет. При этом метод `User.GetAuthQRLink` зависает в синхронном и асинхронном вариантах.

**Comment by shuryak** [comment]
Получил интересный результат в интерактивном C#:

![image](https://user-images.githubusercontent.com/46221547/212503791-d39a3f1b-8858-4771-b00f-8b1dcee6c300.png)

**Comment by shuryak** [comment]
```
Target process has exited during evaluation of instance method System.Threading.Tasks.Task`1 ::get_Result() with actual parameters System.Threading.Tasks.Task`1[Yandex.Music.Api.Models.Common.YResponse`1[Yandex.Music.Api.Models.Queue.YQueueItemsContainer]]. This may possibly happen due to StackOverflowException. This method has been disabled to evaluate
```

**Comment by shuryak** [comment]
Код такого вида с `await` работает для всех методов:

```csharp
private async void button1_Click(object sender, EventArgs e)
        {
            YQueueItem a = await Smth();
            MessageBox.Show(a.Id);
        }

        private async Task<YQueueItem> Smth()
        {
            YandexMusicApi api = new();
            AuthStorage authStorage = new();
            
            await api.User.AuthorizeAsync(authStorage, "Токен");

            List<YQueueItem> items = (await api.Queue.ListAsync(authStorage)).Result.Queues;

            return items[0];
        }
```

На самом деле, я слабо разбираюсь в конкурентности в C#.

**Comment by shuryak** [comment]
Видимо, проблема где-то здесь. Как раз здесь условная компиляция. Возможно, для Windows Forms, по какой-то причине, `client` вообще не компилируется.

![image](https://user-images.githubusercontent.com/46221547/212519510-c023abd3-8e32-49dd-bfd0-9cc1fe8fb866.png)

**Comment by shuryak** [comment]
Но тогда получается совсем странно. Для каких-то методов работает, а для каких-то — нет, хотя все они проходят через этот код.

**Comment by shuryak** [comment]
На самом деле работают все методы, кроме тех, что связаны с получением объектов для авторизации, таких как QR-коды. Потому что, они, видимо, извлекаются из HTML-содержимого...

**Comment by shuryak** [comment]
Таким образом проблема в методе `GetCsrfTokenAsync`.

**Comment by K1llMan** [comment]
Я проверю, возможно, что намудрил с асинхронной цепочкой вызовов. Вообще там сначала должна сессия создаваться для новой авторизации, потом вызываться метод получения объекта для авторизации, например, QR, и потом он должен передаваться в AuthorizeByQR. После этого вызывается получение токена.
@martin211 можешь пояснить механизм?

**Comment by martin211** [comment]
Если авторизация идет по QR, то сессия создается автоматически.
Для других авторизаций, требуется сначала вызвать `CreateAuthSession()`

**Comment by shuryak** [comment]
Скорее всего, дело в асинхронности, ведь в консольных приложениях всё отрабатывает.

**Comment by shuryak** [comment]
В приложениях ASP.NET Core тоже всё отрабатывает. Пока что проблема замечена только в WIndows Forms.

**Comment by K1llMan** [comment]
Могу только предположить, что блокируется основной поток приложения. Поэтому вызовы длительных операций следует выполнять в отдельном потоке и вынести из конструктора.

**Comment by K1llMan** [comment]
> Когда пофиксишь?

Что пофикшу? И кто ты такой?

**Comment by K1llMan** [comment]
В версию 1.3.6 добавлены асинхронные методы.
