### ISSUE TITLE
Ошибка создания сессии авторизации без DebugSettings

### ISSUE THREAD

**Issue by shuryak** [K1llMan/Yandex.Music.Api#16]
Если не задать параметр `DebugSettings settings`, отличный от `null` в конструкторе `AuthStorage`, то `CreateAuthSession()` выдаст ошибку десериализации.

![image](https://user-images.githubusercontent.com/46221547/212774101-f9a8360f-fedc-4750-a11a-ed1daec8961c.png)

![image](https://user-images.githubusercontent.com/46221547/212774278-0bebc3f6-cfdd-4dca-a3b2-c90331c42153.png)

**Comment by shuryak** [comment]
Ошибка в `CommonRequestProvider` в выражении `return` при работе с дебагом:

```csharp
public virtual async Task<T> GetDataFromResponseAsync<T>(YandexMusicApi api, HttpResponseMessage response)
{
    string result = await response.Content.ReadAsStringAsync();

    JsonSerializerSettings settings = new() {
        Converters = new List<JsonConverter> {
            new YExecutionContextConverter(api, storage)
        }
    };

    try
    {
        return storage.Debug != null
            ? storage.Debug.Deserialize<T>(response.RequestMessage?.RequestUri?.AbsolutePath, result, settings)
            : JsonConvert.DeserializeObject<T>(result, settings);
    }
    catch (Exception ex)
    {
        throw new Exception($"Ошибка десериализации {ex}");
    }
}
```

**Comment by shuryak** [comment]
Если `storage.Debug` не равен `null`, то управление переходит к методу `storage.Debug.Deserialize<T>()`, где на десерилизацию устанавливается кастомный обработчик ошибок (я так понял):

```csharp
public T Deserialize<T>(string url, string json, JsonSerializerSettings settings)
{
    Dictionary<string, List<string>> errors = new();

    settings.Error = (sender, args) =>  {
        int pos = args.ErrorContext.Error.Message.IndexOf("Path", StringComparison.Ordinal);
        string error = args.ErrorContext.Error.Message.Substring(0, pos);
        string path = args.ErrorContext.Error.Message.Substring(pos);
            
        if (!errors.ContainsKey(error))
            errors[error] = new List<string>();
            
            errors[error].Add(path);
        args.ErrorContext.Handled = true;
    };
	
	settings.MissingMemberHandling = MissingMemberHandling.Error;
	
	...
}
```

То есть, дебаггер просто "игнорирует" ошибку, но ошибка есть.

**Comment by shuryak** [comment]
![image](https://user-images.githubusercontent.com/46221547/212778727-51face76-078c-4192-b8ab-a1c241128937.png)

**Comment by shuryak** [comment]
Таким образом, в [`YAuthMethod`](https://github.com/K1llMan/Yandex.Music.Api/blob/3a47ccaa3d8c4b2986be2c637366bd9f86230cbf/src/Yandex.Music.Api/Models/Account/YAuthMethod.cs) следует добавить `Otp` и `Magic`. Видимо у API Яндекс Музыки что-то поменялось. Непонятно, оставлять ли старые поля.

**Comment by shuryak** [comment]
Ещё один неучтённый метод.

![image](https://user-images.githubusercontent.com/46221547/212793980-4b0b2173-39d3-4b16-b011-a10d94c23dd8.png)

**Comment by shuryak** [comment]
Насколько понял, `password` — по обычному паролю, `magic_x_token` — скорее всего, раньше это был QR-код, `magic_link` — скорее всего с подтверждением по электронной почте, `magic` — QR-код теперь, `otp` — *One Time Password* (он же пин-код, он же одноразовый пароль из приложения, **OTP**).

**Comment by K1llMan** [comment]
Это методы авторизации. Надо их добавить в enum. Я добавил только те, что были мне доступны.
