### ISSUE TITLE
Возможности API

### ISSUE THREAD

**Issue by Levandeyn** [K1llMan/Yandex.Music.Api#2]
Хотелось бы узнать, можно ли с помощью данного API получить список абсолютно всех треков по исполнителю, чтобы из них сформировать плейлист? Своими силами удалось получить только количество треков для определённого исполнителя.

**Comment by K1llMan** [comment]
Можно попробовать запросить информацию об артисте, там есть список альбомов и плейлистов. Из них можно достать список треков.

**Comment by Levandeyn** [comment]
Спасибо за ответ! Решил эту проблему с помощью WebRequests, получаю id всех треков путём скачивания всей страницы с треками исполнителя.

**Comment by mediaexplorer74** [comment]
> Спасибо за ответ! Решил эту проблему с помощью WebRequests, получаю id всех треков путём скачивания всей страницы с треками исполнителя.

Супер. Надеюсь, repo с результатом выложите на Гитхаб...

**Comment by Levandeyn** [comment]
> > Спасибо за ответ! Решил эту проблему с помощью WebRequests, получаю id всех треков путём скачивания всей страницы с треками исполнителя.
> 
> Супер. Надеюсь, repo с результатом выложите на Гитхаб...

С гитхабом, конечно, слабо знаком. Но когда доделаю полностью, попытаюсь выложить

**Comment by mediaexplorer74** [comment]
> Можно попробовать запросить информацию об артисте, там есть список альбомов и плейлистов. Из них можно достать список треков.

Еще один вопрос по возможностям API. Какая у вас минимально поддерживаемая версия сборки Windows? Очень хотелось бы 15063, так как это актуально для "последних из Магикан" (тех, кто до сих пор юзает Windows 10 Mobile). Я тоже делал форк Yandex.Music.Api, но не  Min OS Build опустить лишь до 16299 :( Соответственно, UWP приложение, которое было бы минимальным аналогом Я.Музыки для винфонов, сделать не выходит

**Comment by K1llMan** [comment]
> Еще один вопрос по возможностям API. Какая у вас минимально поддерживаемая версия сборки Windows? 
Нужно соотносить с доступной версией .Net. Сейчас сборка ориентирована на net5.0. Изначально она собиралась под netcoreapp3.1. Я думаю, что можно настроить несколько целевых версий для сборки.

**Comment by mediaexplorer74** [comment]
> > Еще один вопрос по возможностям API. Какая у вас минимально поддерживаемая версия сборки Windows?
> 
> Нужно соотносить с доступной версией .Net. Сейчас сборка ориентирована на net5.0. Изначально она собиралась под netcoreapp3.1. Я думаю, что можно настроить несколько целевых версий для сборки.

Ух, net 5.0 это круто. Win SDK 15063 "дружит" лишь с библиотеками .net standard 1.4

**Comment by K1llMan** [comment]
> Ух, net 5.0 это круто. Win SDK 15063 "дружит" лишь с библиотеками .net standard 1.4 . 

Проверил. Большинство классов доступно с netstandard2.0. Разве что делать ветку с версией под старые версии и вручную менять на устаревшие классы. В принципе и в старых версиях весь функционал доступен.

**Comment by mediaexplorer74** [comment]
> > Ух, net 5.0 это круто. Win SDK 15063 "дружит" лишь с библиотеками .net standard 1.4 .
> 
> Проверил. Большинство классов доступно с netstandard2.0. Разве что делать ветку с версией под старые версии и вручную менять на устаревшие классы. В принципе и в старых версиях весь функционал доступен.

Всё верно, 2.0 было бы прекрасно. Через Замарин и на Андроиде, и на айОсе вполне этот стандарт доступен, работает все на ура... Кроме убитого ВинМобайла, эх.  Майки не дотянули до поддержки 2.0. Проект Polaris был свернут за неделю до релиза. Мол, из-за глючности, как ходят легенды. Извините за оффтопик, просто раскрыл причины, почему дело труба.  Вы, насколько по диагонали изучил код, оч классный C# программист. Мечты, вдруг потихоньку branch 1.4 сделаете и как-то хоть лайтовую версию библиотечки отрефакторите ) Поиск по артисту, проигрывание треков . Яндекс. Музыка просто того, исчезла из Магазина (она терь только для ветки PC, не Mobile), оттого и yandex.music.api так стал всех интересовать )

**Comment by TheNexoOne** [comment]
Добрый вечер, возможно не совсем по теме, но хотелось бы уточнить. А может ли данный API получать текущий играющий трек?
