### ISSUE TITLE
Исключение при попытке загрузить трек

### ISSUE THREAD

**Issue by Demaxd** [K1llMan/Yandex.Music.Api#21]
Выдается ArgumentNullException ("Value can not be null. Parameter: sourse") при загрузке трека в методе YTrackAPI.GetFileLink
![image](https://user-images.githubusercontent.com/65785412/215069699-a49dbf0b-44de-4023-b22b-0b1bb5358bf6.png)

**Comment by K1llMan** [comment]
Что содержится в trackModel?

**Comment by Demaxd** [comment]
> Что содержится в trackModel?

YSearchTrackModel

**Comment by K1llMan** [comment]
Неправильно оформлен запрос. Надо у YSearchTrackModel вызвать GetKey().ToString(), чтобы получить корректный идентификатор трека.

**Comment by Demaxd** [comment]
> Неправильно оформлен запрос. Надо у YSearchTrackModel вызвать GetKey().ToString(), чтобы получить корректный идентификатор трека.

Пробую GetTrack с корректным id вызывать, ошибка при загрузке файла все равно остается, хотя в YTrack всё правильно определяется

**Comment by K1llMan** [comment]
Нужен id для теста.

**Comment by Demaxd** [comment]
Я пробую на 70217990,  выдает одинаковый id при любом из двух способов вызова GetTrack

**Comment by K1llMan** [comment]
Проверил, в тесте всё корректно. Можно добавить id в TrackTest.cs 

```
// Metallica - Enter Sandman
private string trackId = "57703";
```

для клиента и проверить, без авторизации полминуты должен сохранить в Yandex.Music.Api\src\Yandex.Music.Client.Tests\bin\Debug\net5.0\test.mp3

**Comment by Demaxd** [comment]
В тесте всё работает, непонятно, буду пытаться дальше
