### ISSUE TITLE
Возможности API

### ISSUE THREAD

**Issue by TheNexoOne** [K1llMan/Yandex.Music.Api#24]
Здравствуйте, подскажите пожалуйста, может ли данный API получать данные о текущем проигрываемом треке?

**Comment by K1llMan** [comment]
Здравствуйте. Может, если пользоваться способом, который предлагается в чате телеграмма, и получать трек через очередь. API для очередей добавлено.

**Comment by TheNexoOne** [comment]
Прошу прощения за возможно глупый вопрос, а как попасть в чат телеграмма? Спасибо за ответ!

**Comment by K1llMan** [comment]
[Тут](https://t.me/yandex_music_api)
