### ISSUE TITLE
Возможность скачивания треков из своей коллекции  Yandex Music

### ISSUE THREAD

**Issue by Dims-M** [K1llMan/Yandex.Music.Api#3]
Здраствуйте.
А есть возможность с помощью этой библиотеки скачивать песни(треки, подкасты) по ссылкам с сервиса Yandex Music??

**Comment by K1llMan** [comment]
Да. Через метод API.Track.Get. Только необходимо предварительно преобразовать ссылку в идентификатор трека. Идентификатор имеет формат "<id альбома>:<id трека>", ссылки из Яндекса имеют вид https://music.yandex.ru/album/<id альбома>/track/<id трека>

**Comment by Dims-M** [comment]
> Да. Через метод API.Track.Get. Необходимо предварительное преобразование посилана в идентификатор трека. Идентификатор имеет формат "<id альбома>:<id трека>", ссылки из Яндекса имеют вид https://music.yandex.ru/album/ <id альбома>/track/<id трека>

Спасибо.
