### ISSUE TITLE
Не работают ссылки сезонных плейлистов

### ISSUE THREAD

**Issue by BloodyBaRGaIn** [K1llMan/Yandex.Music.Api#31]
При получении плейлиста Api.GetPlaylist("yamusic-summer2023", "7934310") (с другими ID так же, пробовал эти плейлисты с разных аккаунтов) возникает исключение System.Exception с сообщением:
Ошибка десериализации System.InvalidOperationException: Current error context error is different to requested error.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.GetErrorContext(Object currentObject, Object member, String path, Exception error)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled(Object currentObject, JsonContract contract, Object keyValue, IJsonLineInfo lineInfo, String path, Exception ex)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Yandex.Music.Api.Common.Providers.CommonRequestProvider.GetDataFromResponseAsync[T](YandexMus
icApi api, HttpResponseMessage response)

В методе public virtual async Task<T> GetDataFromResponseAsync<T>(YandexMusicApi api, HttpResponseMessage response) получен JSON в текстовом формате, в нем присутствует вся информация о треках (сравнил с результатом по запросу плейлиста другого типа)

**Comment by BloodyBaRGaIn** [comment]
[Нерабочий.txt](https://github.com/K1llMan/Yandex.Music.Api/files/12563263/default.txt)
[Рабочий.txt](https://github.com/K1llMan/Yandex.Music.Api/files/12563264/default.txt)

Сохранил два JSON (переменная 'text') перед вызовом метода деселиализации
public virtual async Task<T> GetDataFromResponseAsync<T>(YandexMusicApi api, HttpResponseMessage response)
...
result = JsonConvert.DeserializeObject<T>(text, settings);

**Comment by BloodyBaRGaIn** [comment]
Если при инициализации клиента указать DebugSettings, то все работает
`IDebugWriter writer = new DefaultDebugWriter("responses", "log.txt");

_client = new(new DebugSettings(writer)
{
    ClearDirectory = true,
    SaveResponse = true
});`

**Comment by K1llMan** [comment]
Отсутствует в перечислении тип плейлиста "summerrewind2023". Только я не знаю, что с ними такими делать, потому что они выпускают каждый год подобные плейлисты, а потом убирают.

**Comment by BloodyBaRGaIn** [comment]
Может, попробовать отказаться от перечисления и использовать строку?

**Comment by K1llMan** [comment]
Теоретически возможно, но тогда надо будет завязываться на магические значения для пользовательских плейлистов. Можно попробовать в модели оставить текстовое, а в API оставить перечисление для неизменяющихся плейлистов, а сравнивать по строке.

**Comment by BloodyBaRGaIn** [comment]
Я попробовал заменить enum на static class с публичными константными строками, имена которых соответствуют именам перечисления, все прошло без ошибок
Только я не знаю, мне нужно делать форк, если я правильно понимаю механизм?

**Comment by BloodyBaRGaIn** [comment]
> Теоретически возможно, но тогда надо будет завязываться на магические значения для пользовательских плейлистов. Можно попробовать в модели оставить текстовое, а в API оставить перечисление для неизменяющихся плейлистов, а сравнивать по строке.

Если так посудить, названия значений перечисления тоже немного магические)

**Comment by BloodyBaRGaIn** [comment]
Я попробовал выполнить тесты в оригинальном проекте и в "новом", и у меня не все тесты проходят. Норма ли это? Новый тест с сезонным плейлистом проходит

В оригинальном проекте:
![image](https://github.com/K1llMan/Yandex.Music.Api/assets/32248195/4ca47368-ba03-42cf-8d61-99976404ac03)

В "новом":
![image](https://github.com/K1llMan/Yandex.Music.Api/assets/32248195/41a2103a-2267-4aa9-b3dc-6e264af854f6)

**Comment by K1llMan** [comment]
Авторизацию лучше использовать через токен. Тесты должны в большинстве выполняться. Может не работать получение плейлиста Rewind, иногда добавление/удаление не срабатывает. Я завтра постараюсь глянуть.

**Comment by BloodyBaRGaIn** [comment]
Большое спасибо!!!

**Comment by K1llMan** [comment]
Должно быть исправлено в 1.5.0.
