### ISSUE TITLE
Загрузка файлов из своей колекцции

### ISSUE THREAD

**Issue by Dims-M** [K1llMan/Yandex.Music.Api#36]
Здравствуйте.
Спасибо за интересный проект.
Не планируете ли сделать функционал по загрузке треков из своей коллекции или по id ??
Есть расширение для браузера по загрузке. Может как основу для идеи взять.
Скачать музыку 2.0.6

**Comment by K1llMan** [comment]
Здравствуйте. Для загрузки на Яндекс? Или под загрузкой вы имеете ввиду скачку файлов?

**Comment by Dims-M** [comment]
Скачивание файлов))
