### ISSUE TITLE
Добавление своей музыки в коллекцию

### ISSUE THREAD

**Issue by PrepConcedeITIS** [K1llMan/Yandex.Music.Api#37]
Привет! Сейчас не реализован данный функционал, скорее всего по причине того, что используется API от мобильных приложений я.музыки. У меня возникла необходимость использовать этот функционал, поэтому предлагаю со своей стороны реализовать это, но с использованием API с веб версии.
Однако возник вопрос, насколько это будет релевантно в данной библиотеке?

**Comment by K1llMan** [comment]
Привет. Желательно, конечно, использовать один и тот же API, но если для адреса из веб-версии будет достаточно токена, то можно добавить и его. Корневые адреса запросов гибко настраиваются через атрибут.

**Comment by PrepConcedeITIS** [comment]
Хорошо, возьму в работу тогда эту фичу

**Comment by K1llMan** [comment]
В nuget добавлена версия 1.8.0.
