### ISSUE TITLE
Методы для получения данных о музыкальный лейблах

### ISSUE THREAD

**Issue by PrepConcedeITIS** [K1llMan/Yandex.Music.Api#39]
Привет, увидел что в апи не реализован функционал работы с лейблами. В апи есть два эндпоинта:

1. `GET /labels/{id}/artists?page={page}`
2. `GET /labels/{id}/albums?page={page}`

Каждый из них в ответе возвращает массив артистов/альбомов и объект YPager. Хочу законтрибьютить этот функционал.
@K1llMan нет возражений?

**Comment by K1llMan** [comment]
Привет. Да, давай, я не против. Можно сделать ещё тип объекта параметром, как у YLibrarySection, чтобы не плодить запросы.

**Comment by K1llMan** [comment]
Добавлено в версию 1.9.0
