### ISSUE TITLE
"Вы недавно слушали" и раздел "детям"

### ISSUE THREAD

**Issue by PrepConcedeITIS** [K1llMan/Yandex.Music.Api#45]
Привет, в апи сейчас не реализованы следующие эндпоинты:
1. "Вы недавно слушали"
`GET /users/{uid}/contexts?trackCount={trackCount}&types={contexTypeArray}&contextCount={contextsCount}`
2. Детские раздел на лендинге (доступен без авторизации)
`GET /children-landing/catalogue`

Хочу законтрибьютить этот функционал. @K1llMan нет возражений?

**Comment by K1llMan** [comment]
Привет. Я не против. По лендингу, правда, надо бы капитально переделать (https://github.com/K1llMan/Yandex.Music.Api/issues/44#issuecomment-2057637913)
Не знаю, все ли есть эндпоинты, но можно дополнить ещё из https://github.com/acherkashin/yandex-music-open-api/blob/main/src/yandex-music.yaml из landing3, а также по genres тоже ничего нет.

**Comment by K1llMan** [comment]
Закрываю. Другие эндпоинты вынесены в отдельную задачу.
