### ISSUE TITLE
А не планируется ли API по disk.yandex

### ISSUE THREAD

**Issue by Dims-M** [K1llMan/Yandex.Music.Api#5]
Здраствуйте.
 А не планируется работа с Яндекс диском. По аналогии я Яндекс музыкой??

**Comment by Dims-M** [comment]
Спасибо.

**Comment by mediaexplorer74** [comment]
> Здраствуйте. А не планируется работа с Яндекс диском. По аналогии я Яндекс музыкой??

Если интересно, гляньте мой "ремейк" https://github.com/mediaexplorer74/YaD (проект "ЯД"). Делал чисто под себя, для ретро-смартфона Lumia

**Comment by Dims-M** [comment]
> > Здраствуйте. А не планируется работа с Яндекс диском. По аналогии я Яндекс музыкой??
> 
> Если интересно, гляньте мой "ремейк" https://github.com/mediaexplorer74/YaD (проект "ЯД"). Делал чисто под себя, для ретро-смартфона Lumia (.Net Standard 1.4, UWP). Если вдруг мимо Вас пролетало что-то по API Яндекс.Такси (ныне это вроде бы "мега-шарманка" GO со всякой Доставкой жрачки, покером и блэкджеком), был бы оч. признателен (на винфоне есть Я.Такси, но смска не приходит, когда пытаюсь зарегиться)

Спасибо. Обязательно глянем.
