### ISSUE TITLE
System.Exception: 'Ошибка десериализации типа "YSearchAlbumModel".'

### ISSUE THREAD

**Issue by skuill** [K1llMan/Yandex.Music.Api#6]
**Проблема**
Во время выполнения поиска трека по исполнителю и названию наткнулся на следующую ошибку:
![image](https://user-images.githubusercontent.com/19705282/196213281-27326dc9-d41c-48f4-a561-2109afeb1bbf.png)

**Текст ошибки:**
System.Exception: 'Ошибка десериализации типа "YSearchAlbumModel".'
JsonReaderException: Unexpected character encountered while parsing value: {. Path 'result.tracks.results[0].albums[0].labels', line 1, position 1570.

**Как воспроизвести**
Сделать вызов метода 
`public YSearch Search(string searchText, YSearchType searchType, int page = 0)`
из класса `Yandex.Music.Client.YandexMusicClient`
С передачей аргументов:
```
searchText="Parkway Drive - Carrion"
searchType = YSearchType.Track
```

**В чем проблема**
При десериализации результата запроса json в модель `YSearchAlbumModel` поле `public new List<string> Labels { get; set; }` может иметь разные типы внутри.
Например в одном месте:
```
"labels": [
	{
		"id": 445547,
		"name": "Epitaph"
	}
],
```
В другом:
```
"labels": [
	"Epitaph"
],

**Comment by K1llMan** [comment]
Ок. Поправлю. Спасибо за пример.

**Comment by K1llMan** [comment]
Исправил. Пакеты в nuget также обновил.

**Comment by skuill** [comment]
@K1llMan спасибо большое!
