### ISSUE TITLE
Remove redundant async/await statements for API methods

### ISSUE THREAD

**Issue by martin211** [K1llMan/Yandex.Music.Api#9]
At \src\Yandex.Music.Api\API\Y*API.cs classes has wrong definition for async methotds.

` public async Task<YResponse<YLibraryTracks>> GetLikedTracksAsync(AuthStorage storage)
  {
     return await ...;
  }`
No need async/await here. You method already returns a task, async/await must be in the calling code.

**Comment by K1llMan** [comment]
Fixed. Thx.
